import { KeyboardItemProps } from "./interface";

export const IpcKeyboardEvent = 'ipc-keyboard-event'
export const IpcGetRankData = 'ipc-get-rank-data'
export const IpcClearData = 'ipc-clear-data'

export enum EnumKeyboardName {
  ESCAPE = 'ESCAPE',
  ONE = '1',
  TWO = '2',
  THREE = '3',
  FOUR = '4',
  FIVE = '5',
  SIX = '6',
  SEVEN = '7',
  EIGHT = '8',
  NINE = '9',
  ZERO = '0',
  MINUS = 'MINUS',
  EQUALS = 'EQUALS',
  BACKSPACE = 'BACKSPACE',
  TAB = 'TAB',
  Q = 'Q',
  W = 'W',
  E = 'E',
  R = 'R',
  T = 'T',
  Y = 'Y',
  U = 'U',
  I = 'I',
  O = 'O',
  P = 'P',
  SQUARE_BRACKET_CLOSE = 'SQUARE BRACKET CLOSE',
  SQUARE_BRACKET_OPEN = 'SQUARE BRACKET OPEN',
  BACKSLASH = 'BACKSLASH',
  DELETE = 'DELETE',
  CAPS_LOCK = 'CAPS LOCK',
  A = 'A',
  S = 'S',
  D = 'D',
  F = 'F',
  G = 'G',
  H = 'H',
  J = 'J',
  K = 'K',
  L = 'L',
  SEMICOLON = 'SEMICOLON',
  QUOTE = 'QUOTE',
  RETURN = 'RETURN',
  PAGE_UP = 'PAGE UP',
  LEFT_SHIFT = 'LEFT SHIFT',
  Z = 'Z',
  X = 'X',
  C = 'C',
  V = 'V',
  B = 'B',
  N = 'N',
  M = 'M',
  COMMA = 'COMMA',
  DOT = 'DOT',
  FORWARD_SLASH = 'FORWARD SLASH',
  RIGHT_SHIFT = 'RIGHT SHIFT',
  UP_ARROW = 'UP ARROW',
  PAGE_DOWN = 'PAGE DOWN',
  LEFT_CTRL = 'LEFT CTRL',
  LEFT_ALT = 'LEFT ALT',
  LEFT_META = 'LEFT META',
  SPACE = 'SPACE',
  RIGHT_META = 'RIGHT META',
  RIGHT_ALT = 'RIGHT ALT',
  RIGHT_CTRL = 'RIGHT CTRL',
  LEFT_ARROW = 'LEFT ARROW',
  DOWN_ARROW = 'DOWN ARROW',
  RIGHT_ARROW = 'RIGHT ARROW',
}

export const defaultKeyboardData: KeyboardItemProps[][] = [
  [
    { id: EnumKeyboardName.ESCAPE, name: 'Esc' },
    { id: EnumKeyboardName.ONE, name: '1!' },
    { id: EnumKeyboardName.TWO, name: '2@' },
    { id: EnumKeyboardName.THREE, name: '3#' },
    { id: EnumKeyboardName.FOUR, name: '4$' },
    { id: EnumKeyboardName.FIVE, name: '5%' },
    { id: EnumKeyboardName.SIX, name: '6^' },
    { id: EnumKeyboardName.SEVEN, name: '7&' },
    { id: EnumKeyboardName.EIGHT, name: '8*' },
    { id: EnumKeyboardName.NINE, name: '9(' },
    { id: EnumKeyboardName.ZERO, name: '0)' },
    { id: EnumKeyboardName.MINUS, name: '-' },
    { id: EnumKeyboardName.EQUALS, name: '=+' },
    { id: EnumKeyboardName.BACKSPACE, name: 'Backspace', width: '100px' },
    { id: 'Fn', name: 'Fn' },
  ],
  [
    { id: EnumKeyboardName.TAB, name: 'Tab', width: '75px' },
    { id: EnumKeyboardName.Q, name: 'Q' },
    { id: EnumKeyboardName.W, name: 'W' },
    { id: EnumKeyboardName.E, name: 'E' },
    { id: EnumKeyboardName.R, name: 'R' },
    { id: EnumKeyboardName.T, name: 'T' },
    { id: EnumKeyboardName.Y, name: 'Y' },
    { id: EnumKeyboardName.U, name: 'U' },
    { id: EnumKeyboardName.I, name: 'I' },
    { id: EnumKeyboardName.O, name: 'O' },
    { id: EnumKeyboardName.P, name: 'P' },
    { id: EnumKeyboardName.SQUARE_BRACKET_CLOSE, name: '[{' },
    { id: EnumKeyboardName.SQUARE_BRACKET_OPEN, name: ']}' },
    { id: EnumKeyboardName.BACKSLASH, name: '\\|', width: '65px' },
    { id: EnumKeyboardName.DELETE, name: 'Del' },
  ],
  [
    { id: EnumKeyboardName.CAPS_LOCK, name: 'Caps', width: '90px' },
    { id: EnumKeyboardName.A, name: 'A' },
    { id: EnumKeyboardName.S, name: 'S' },
    { id: EnumKeyboardName.D, name: 'D' },
    { id: EnumKeyboardName.F, name: 'F' },
    { id: EnumKeyboardName.G, name: 'G' },
    { id: EnumKeyboardName.H, name: 'H' },
    { id: EnumKeyboardName.J, name: 'J' },
    { id: EnumKeyboardName.K, name: 'K' },
    { id: EnumKeyboardName.L, name: 'L' },
    { id: EnumKeyboardName.SEMICOLON, name: ';:' },
    { id: EnumKeyboardName.QUOTE, name: '\"\'' },
    { id: EnumKeyboardName.RETURN, name: 'Enter', width: '105px' },
    { id: EnumKeyboardName.PAGE_UP, name: 'Pgup' },
  ],
  [
    { id: EnumKeyboardName.LEFT_SHIFT, name: 'Shift', width: '105px' },
    { id: EnumKeyboardName.Z, name: 'Z' },
    { id: EnumKeyboardName.X, name: 'X' },
    { id: EnumKeyboardName.C, name: 'C' },
    { id: EnumKeyboardName.V, name: 'V' },
    { id: EnumKeyboardName.B, name: 'B' },
    { id: EnumKeyboardName.N, name: 'N' },
    { id: EnumKeyboardName.M, name: 'M' },
    { id: EnumKeyboardName.COMMA, name: ',<' },
    { id: EnumKeyboardName.DOT, name: '.>' },
    { id: EnumKeyboardName.FORWARD_SLASH, name: '/?' },
    { id: EnumKeyboardName.RIGHT_SHIFT, name: 'Shift', width: '85px' },
    { id: EnumKeyboardName.UP_ARROW, name: 'Up' },
    { id: EnumKeyboardName.PAGE_DOWN, name: 'Pgdn' },
  ],
  [
    { id: EnumKeyboardName.LEFT_CTRL, name: 'Ctrl' },
    { id: 'Fn', name: 'Fn' },
    { id: EnumKeyboardName.LEFT_ALT, name: 'Alt' },
    { id: EnumKeyboardName.LEFT_META, name: 'Meta' },
    { id: EnumKeyboardName.SPACE, name: 'Space', width: '320px' },
    { id: EnumKeyboardName.RIGHT_META, name: 'Meta' },
    { id: EnumKeyboardName.RIGHT_ALT, name: 'Alt' },
    { id: EnumKeyboardName.RIGHT_CTRL, name: 'Ctrl' },
    { id: EnumKeyboardName.LEFT_ARROW, name: 'Left' },
    { id: EnumKeyboardName.DOWN_ARROW, name: 'Down' },
    { id: EnumKeyboardName.RIGHT_ARROW, name: 'Right' },
  ]
]
