export const IpcKeyboardEvent = 'ipc-keyboard-event';
export const IpcGetRankData = 'ipc-get-rank-data';
export const IpcClearData = 'ipc-clear-data';
export const IpcGetDatabaseFilename = 'IPC_GET_DATABASE_FILENAME';
export const IpcSwitchDatabaseFilename = 'IPC_SWITCH_DATABASE_FILENAME';
export const IpcSaveDatabaseFilename = 'IPC_SAVE_DATABASE_FILENAME';
export const IpcRestartApp = 'IPC_RESTART_APP';

export const StorageKeyboardType = 'storage-key-board-type';
export const AppConfigStoreKey = 'ELECTRON_APP_CONFIG_STORE_KEY';
export const DatabaseFilename = 'DATABASE_FILENAME';

export const DefaultDatabaseName = 'keyboard-listener.db';

// eslint-disable-next-line no-shadow
export enum EnumKeyboardName {
  BACKTICK = 'BACKTICK',
  ESCAPE = 'ESCAPE',
  ONE = '1',
  TWO = '2',
  THREE = '3',
  FOUR = '4',
  FIVE = '5',
  SIX = '6',
  SEVEN = '7',
  EIGHT = '8',
  NINE = '9',
  ZERO = '0',
  MINUS = 'MINUS',
  EQUALS = 'EQUALS',
  BACKSPACE = 'BACKSPACE',
  TAB = 'TAB',
  Q = 'Q',
  W = 'W',
  E = 'E',
  R = 'R',
  T = 'T',
  Y = 'Y',
  U = 'U',
  I = 'I',
  O = 'O',
  P = 'P',
  SQUARE_BRACKET_CLOSE = 'SQUARE BRACKET CLOSE',
  SQUARE_BRACKET_OPEN = 'SQUARE BRACKET OPEN',
  BACKSLASH = 'BACKSLASH',
  DELETE = 'DELETE',
  CAPS_LOCK = 'CAPS LOCK',
  A = 'A',
  S = 'S',
  D = 'D',
  F = 'F',
  G = 'G',
  H = 'H',
  J = 'J',
  K = 'K',
  L = 'L',
  SEMICOLON = 'SEMICOLON',
  QUOTE = 'QUOTE',
  RETURN = 'RETURN',
  PAGE_UP = 'PAGE UP',
  LEFT_SHIFT = 'LEFT SHIFT',
  Z = 'Z',
  X = 'X',
  C = 'C',
  V = 'V',
  B = 'B',
  N = 'N',
  M = 'M',
  COMMA = 'COMMA',
  DOT = 'DOT',
  FORWARD_SLASH = 'FORWARD SLASH',
  RIGHT_SHIFT = 'RIGHT SHIFT',
  UP_ARROW = 'UP ARROW',
  PAGE_DOWN = 'PAGE DOWN',
  LEFT_CTRL = 'LEFT CTRL',
  LEFT_ALT = 'LEFT ALT',
  LEFT_META = 'LEFT META',
  SPACE = 'SPACE',
  RIGHT_META = 'RIGHT META',
  RIGHT_ALT = 'RIGHT ALT',
  RIGHT_CTRL = 'RIGHT CTRL',
  LEFT_ARROW = 'LEFT ARROW',
  DOWN_ARROW = 'DOWN ARROW',
  RIGHT_ARROW = 'RIGHT ARROW',
}
