import { app, BrowserWindow, ipcMain } from 'electron';
import { GlobalKeyboardListener } from 'node-global-key-listener';
import { IpcClearData, IpcGetRankData, IpcKeyboardEvent } from './constant';
import KeyboardDataManager from './KeyboardDataManager';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

let mainWindow: BrowserWindow
let globalKeyBoardListener: GlobalKeyboardListener
let registeredIpcMainHandler = false

const keyboardDataManager = new KeyboardDataManager()
keyboardDataManager.load()

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  // eslint-disable-line global-require
  app.quit();
}

const handleIpcGetRankData = async () => {
  return keyboardDataManager.getRankList(10)
}

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 600,
    width: 916,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // 绑定下全局事件
  if (!globalKeyBoardListener) {
    const globalKeyBoardListener = new GlobalKeyboardListener()
    globalKeyBoardListener.addListener((e) => {
      if (e.state === 'DOWN') {
        // console.log(e.name)
        const data = { name: e.name }
        keyboardDataManager.append(data)
        // // 如果当前存在窗口的话，渲染动画
      }
      if (mainWindow) {
        mainWindow.webContents.send(IpcKeyboardEvent, e)
      }
    })
  }

  if (!registeredIpcMainHandler) {
    ipcMain.handle(IpcGetRankData, handleIpcGetRankData)
    ipcMain.handle(IpcClearData, () => keyboardDataManager.clearData())
    registeredIpcMainHandler = true
  }

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
  console.log('window-all-closed')
  mainWindow = undefined
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
