export function keyboardNameToId (name: string) {
  // console.log(name)
  const map: {
    [k:string]: string
  } = {
    ESCAPE: 'ESCAPE',
    1: 'ONE',
    2: 'TWO',
    3: 'THREE',
    4: 'FOUR',
    5: 'FIVE',
    6: 'SIX',
    7: 'SEVEN',
    8: 'EIGHT',
    9: 'NINE',
    0: 'ZERO',
    MINUS: 'MINUS',
    EQUALS: 'EQUALS',
    BACKSPACE: 'BACKSPACE',
    TAB: 'TAB',
    Q: 'Q',
    W: 'W',
    E: 'E',
    R: 'R',
    T: 'T',
    Y: 'Y',
    U: 'U',
    I: 'I',
    O: 'O',
    P: 'P',
    'SQUARE BRACKET CLOSE': 'SQUARE_BRACKET_CLOSE',
    'SQUARE BRACKET OPEN': 'SQUARE_BRACKET_OPEN',
    BACKSLASH: 'BACKSLASH',
    DELETE: 'DELETE',
    'CAPS LOCK': 'CAPS_LOCK',
    A: 'A',
    S: 'S',
    D: 'D',
    F: 'F',
    G: 'G',
    H: 'H',
    J: 'J',
    K: 'K',
    L: 'L',
    SEMICOLON: 'SEMICOLON',
    QUOTE: 'QUOTE',
    RETURN: 'RETURN',
    'PAGE UP': 'PAGE_UP',
    'LEFT SHIFT': 'LEFT_SHIFT',
    Z: 'Z',
    X: 'X',
    C: 'C',
    V: 'V',
    B: 'B',
    N: 'N',
    M: 'M',
    COMMA: 'COMMA',
    DOT: 'DOT',
    'FORWARD SLASH': 'FORWARD_SLASH',
    'RIGHT SHIFT': 'RIGHT_SHIFT',
    'UP ARROW': 'UP_ARROW',
    'PAGE DOWN': 'PAGE_DOWN',
    'LEFT CTRL': 'LEFT_CTRL',
    'LEFT ALT': 'LEFT_ALT',
    'LEFT META': 'LEFT_META',
    SPACE: 'SPACE',
    'RIGHT META': 'RIGHT_META',
    'RIGHT ALT': 'RIGHT_ALT',
    'RIGHT CTRL': 'RIGHT_CTRL',
    'LEFT ARROW': 'LEFT_ARROW',
    'DOWN ARROW': 'DOWN_ARROW',
    'RIGHT ARROW': 'RIGHT_ARROW',
  }

  return map[name]
}

module.exports = {
  keyboardNameToId
}